version: '3.9'
services:
  server:
    container_name: ${PROJECT_NAME}-server
    image: ${PROJECT_NAME}/server
    build: ./.docker/server
    env_file:
      - ./.env
    environment:
      # Verify the .env file.
      - PROJECT_NAME=${PROJECT_NAME:?!!! ERROR !!! .env file not found at the root directory!}
      # Environment variables.
      # Every variable defined here must also be defined in:
      # /.docker/server/apache/sites-enabled/main.conf
      - MYSQL_USER=${MYSQL_APP_USER}
      - MYSQL_PASS=${MYSQL_APP_PASS}
      - MYSQL_ROOT_PASS=""
      - MYSQL_APP_USER=""
      - MYSQL_APP_PASS=""
      - MYSQL_VIEW_USER=""
      - MYSQL_VIEW_PASS=""
      - PMA_USER=""
      - PMA_PASS=""
      - COMPOSE_PROJECT_NAME=""
    volumes:
      # Working Directory
      - ./src/:/var/www/html/
      # Logs
      #TODO: Map Docker host logs.
      #https://www.google.com/search?client=firefox-b-d&q=docker+log+location
      - ./data/logs/apache/:/var/log/apache2/
      - ./data/logs/php/:/var/log/php/
      - ./data/tests/:/var/tests/
    networks:
      - backend
    ports:
      - "80:80"
      - "443:443"

#  mysql:
#    container_name: ${PROJECT_NAME}-mysql
#    image: mysql:8
#    command: --default-authentication-plugin=mysql_native_password
#    restart: always
#    environment:
#      - MYSQL_ROOT_PASSWORD=$MYSQL_ROOT_PASSWORD
#      - MYSQL_USER=$MYSQL_USER
#      - MYSQL_PASSWORD=$MYSQL_PASSWORD
#    networks:
#      - backend
#    ports:
#      - "3306:3306"
#    volumes:
#      # Data
#      - ./data/mysql:/var/lib/mysql
#
#  phpmyadmin:
#    container_name: ${PROJECT_NAME}-phpmyadmin
#    image: phpmyadmin/phpmyadmin
#    environment:
#      - PMA_ARBITRARY=1
#      - PMA_HOST=mysql
#      - PMA_USER=root
#      - PMA_PASSWORD=root
#    ports:
#      - "8080:80"
#    networks:
#      - backend
#    volumes:
#      # Config
#      - ./.docker/phpmyadmin/uploads.ini:/usr/local/etc/php/conf.d/php-phpmyadmin.ini

networks:
  backend:
    name: ${PROJECT_NAME}-backend
