version: '3.9'
services:
  php:
    container_name: ${PROJECT_NAME}-php
    image: ${PROJECT_NAME}/server
    build: ./.docker/php
    volumes:
      # Working Directory
      - ./src/:/var/www/html/
    networks:
      - backend
#    ports:
#      - "80:80"
#      - "443:443"

#  mysql:
#    container_name: ${PROJECT_NAME}-mysql
#    image: mysql:8
#    command: --default-authentication-plugin=mysql_native_password
#    restart: always
#    environment:
#      - MYSQL_ROOT_PASSWORD=$MYSQL_ROOT_PASSWORD
#      - MYSQL_USER=$MYSQL_USER
#      - MYSQL_PASSWORD=$MYSQL_PASSWORD
#    networks:
#      - backend
#    ports:
#      - "3306:3306"
#    volumes:
#      # Data
#      - ./data/mysql:/var/lib/mysql
#
#  phpmyadmin:
#    container_name: ${PROJECT_NAME}-phpmyadmin
#    image: phpmyadmin/phpmyadmin
#    environment:
#      - PMA_ARBITRARY=1
#      - PMA_HOST=mysql
#      - PMA_USER=root
#      - PMA_PASSWORD=root
#    ports:
#      - "8080:80"
#    networks:
#      - backend
#    volumes:
#      # Config
#      - ./.docker/phpmyadmin/uploads.ini:/usr/local/etc/php/conf.d/php-phpmyadmin.ini

networks:
  backend:
    name: ${PROJECT_NAME}-backend
